/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unisa.adc.auctionProject.GUI;

import it.unisa.adc.auctionProject.AuctionMechanismImpl;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alfonso
 */
public class checkAuctionFrame extends javax.swing.JFrame {
private mainFrame rifMain;
private AuctionMechanismImpl peerRif;
    /**
     * Creates new form checkAuctionFrame
     */
    public checkAuctionFrame(mainFrame f,AuctionMechanismImpl peer) {
        initComponents();
        rifMain =f;
        this.peerRif=peer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNameAuction = new javax.swing.JTextField();
        chechStatuNow = new javax.swing.JButton();
        checkDescription = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome Asta da Controllare");

        txtNameAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameAuctionActionPerformed(evt);
            }
        });

        chechStatuNow.setBackground(new java.awt.Color(255, 0, 9));
        chechStatuNow.setText("Visualizza Stato");
        chechStatuNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chechStatuNowMouseClicked(evt);
            }
        });

        checkDescription.setText("Includi Descrizione");
        checkDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNameAuction)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chechStatuNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNameAuction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chechStatuNow, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameAuctionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameAuctionActionPerformed

    private void chechStatuNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chechStatuNowMouseClicked
        // TODO add your handling code here:
        String name = txtNameAuction.getText();
        String status="";
        String description="";
        
        if(name.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Errore Dati di Input");
        }else
        {
            try {
                if(checkDescription.isSelected()){
                     description = peerRif.getDescriptionByName(name);
                    
                }
                status =peerRif.checkAuction(name);
            } catch (IOException ex) {
                Logger.getLogger(checkAuctionFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(checkAuctionFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            rifMain.outConsoleSet(status);
            rifMain.outConsoleSet(description);
             this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
            
    }//GEN-LAST:event_chechStatuNowMouseClicked

    private void checkDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDescriptionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkDescriptionActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chechStatuNow;
    private javax.swing.JCheckBox checkDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNameAuction;
    // End of variables declaration//GEN-END:variables
}
