/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unisa.adc.auctionProject.GUI;

import it.unisa.adc.auctionProject.AuctionMechanismImpl;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import it.unisa.adc.auctionProject.CreateAuctionException;


/**
 *
 * @author alfonso
 */
public class createAuctionFrame extends javax.swing.JFrame {
private AuctionMechanismImpl peerRif;
    /**
     * Creates new form createAuctionFrame
     */
     private mainFrame rifMain ;
    public createAuctionFrame(mainFrame f,AuctionMechanismImpl peer) {
        initComponents();
       rifMain =f;
       this.peerRif=peer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        auctionNameCreate = new javax.swing.JTextField();
        auctionExpCreate = new javax.swing.JTextField();
        auctionDescCreate = new javax.swing.JTextField();
        reservePriceCreate = new javax.swing.JTextField();
        btnCreateNow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Crea Asta");

        jLabel2.setText("Nome Asta");

        jLabel3.setText("Prezzo Riserva");

        jLabel4.setText("Descrizione");

        jLabel5.setText("Fine Asta");

        auctionExpCreate.setText("dd/MM/yyyy hh:mm");
        auctionExpCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auctionExpCreateActionPerformed(evt);
            }
        });

        btnCreateNow.setBackground(new java.awt.Color(76, 174, 51));
        btnCreateNow.setText("Crea Ora");
        btnCreateNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateNowMouseClicked(evt);
            }
        });
        btnCreateNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(auctionNameCreate)
                            .addComponent(auctionDescCreate)
                            .addComponent(auctionExpCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(reservePriceCreate))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCreateNow, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auctionNameCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auctionDescCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auctionExpCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservePriceCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateNow, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        auctionNameCreate.getAccessibleContext().setAccessibleName("createName");
        auctionExpCreate.getAccessibleContext().setAccessibleName("expireCreate");
        auctionDescCreate.getAccessibleContext().setAccessibleName("descCreate");
        reservePriceCreate.getAccessibleContext().setAccessibleName("reserveCreate");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateNowActionPerformed

    private void btnCreateNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateNowMouseClicked
        // TODO add your handling code here:
        
        try {
            String name = auctionNameCreate.getText();
            String desc = auctionDescCreate.getText();
            if(name.equalsIgnoreCase("")|| desc.equalsIgnoreCase("")||name.chars().allMatch(Character::isDigit)|| desc.chars().allMatch(Character::isDigit))
                throw new CreateAuctionException("Il nome e la descrizione dell'asta non possono essere vuoti o valori unicamente numerici");
            double reservePrice = Double.parseDouble(reservePriceCreate.getText());
            Date expDate = new SimpleDateFormat("dd/MM/yyyy hh:mm").parse(auctionExpCreate.getText());
           
            
            if(expDate.before(new Date(System.currentTimeMillis() + 3600 * 1000)))
                throw new CreateAuctionException("La data di creazione deve essere successiva alla data corrente locale");
            
            if(reservePrice<=0)
                throw new CreateAuctionException("Il prezzo di riserva non può essere negativo o pari a 0");
            
            if(peerRif.createAuction(name, expDate, reservePrice, desc)){
                rifMain.outConsoleSet("Asta "+name+" Creata con successo");
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
            }else{
                throw new CreateAuctionException("Errore nella Creazione Dell'asta");
            }
            
        }catch(CreateAuctionException er){
            JOptionPane.showMessageDialog(this, er.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Errore Dati di Input");
            //Logger.getLogger(createAuctionFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnCreateNowMouseClicked

    private void auctionExpCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auctionExpCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auctionExpCreateActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField auctionDescCreate;
    private javax.swing.JTextField auctionExpCreate;
    private javax.swing.JTextField auctionNameCreate;
    private javax.swing.JButton btnCreateNow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField reservePriceCreate;
    // End of variables declaration//GEN-END:variables
}
